### ISSUE TITLE
linkage issues with gcc 7.2, static window edition

### ISSUE THREAD

**Issue by barawn** [nichol77/libRootFftwWrapper#1]
This is going to be a bit of a disjoint bug, because I'm still working out exactly what's going on.

Upgrading to gcc 7.2 somehow made a lot of linkage issues show up for libRootFftwWrapper. I'm still tracing down exactly what's going on. One thing I found is that part of the problem is the declaration of static const windows in the FFTwindow.h *header* - that is,

static const KaiserWindow KAISER_WINDOW;
(etc.)

I don't know why those are declared there. I'm guessing the idea is that they're supposed to be a global instance that anyone can use (hence why the welchPeriodogram constructor uses a default &GAUSSIAN_WINDOW) for that.

Except if that's the intent, this isn't how you're supposed to do it. Since this is put in the header, each compilation file creates a "const KaiserWindow" object named KAISER_WINDOW, but doesn't emit a global symbol for it. That's what static does outside the context of classes (it's different in classes, where static means the object created is independent of a class instance). 

I would've thought this is still okay (although possibly not ideal), but I think what the problem is that the "value()" function is virtual, and it's not *declared* except in the FFTWindow.cxx function. So there's a function reference in FFTWindow.cxx for the "value()" function, but since the object's declared static, the linker is looking for one *in the compilation file*, and can't find it. This is a guess, though.

However, there's an easy solution. What should have been done is, in the header, declare the object extern:

extern const KaiserWindow KAISER_WINDOW;

which tells the linker "there's a const KaiserWindow object called KAISER_WINDOW somewhere, just keep it as an unlinked symbol and the linker'll find it". Then, in FFTWindow.cxx, add

const KaiserWindow KAISER_WINDOW;

(no static, since you want it to emit the symbol so it can be linked against).

With the static declarations, when compiling, you get:
icemc.o: In function `FFTtools::KaiserWindow::KaiserWindow(double)':
/path/to/file/include/FFTWindow.h:96: undefined reference to `vtable for FFTtools::KaiserWindow`

With the extern declaration, those go away. (Still a bucket-ton of other linkage errors, though).

If that's the correct interpretation of what the 'static const' windows are for, I can go ahead and submit a pull request switching them all over to extern declarations and instantiating them in the FFTWindow.cxx file.

**Comment by cozzyd** [comment]
Hi Patrick,

What OS is this? Can't reproduce with gcc 7.2 on Fedora. If you are in a debian system try adding -Wl,--no-as-needed to the linker flags in icemc (or try a cmake build). The static consts do mean each compilation unit has its own (which increases compile time somewhat) but I think should be ok (if inelegant). The fact that it's declared static doesn't affect where it looks for the class implementation (you can make static instances of whatever anywhere).  It's possible that it somehow interacts properly with the default -Wl,-as-needed behavior on Debian systems. I'll look into it after I get back from vacation. 

Thanks,
-Cosmin

**Comment by barawn** [comment]
Yeah, that did it, and the reason why switching to an extern rather than static also fixes the problem there is because declaring it extern specifically makes it an object linked in, rather than a function loaded through another library's function. It looks like --as-needed suddenly became the default after that upgrade, and everything went poof. Looks like it's icemc's Makefile's problem, then.
